Added a menu to the `/upgrade` command
A5rocks/code-jam-11 pull request #29
Opened 2024-07-24 16:28 UTC by LuckElixir

Currently the view does not call any other external commands.

Should there be any changes on how the view behaves?

2024-07-24 16:46 UTC, A5rocks requested changes

2024-07-24 16:46 UTC, A5rocks commented on app/__main__.py
> +            await interaction.message.edit(view=self)
IMO, we shouldn't edit the source message but instead confirm in a new message like you do later. This way someone can upgrade CPS multiple times. (Similarly for other things)

2024-07-24 16:46 UTC, A5rocks commented on app/__main__.py
> +        self.stop()
This doesn't make sense for persistent views

2024-07-24 16:46 UTC, A5rocks commented on app/__main__.py
> +        self.stop()
We *could* make all buttons disabled but I think cancelling persistent views is unnecessary.

2024-07-24 16:46 UTC, A5rocks commented on app/__main__.py
> +    await interaction.response.send_message(embed=embed, view=view)
TBH should the upgrade menu say costs (just put "[cost]" for now) and be ephemeral? That might be nicer, what do you think?

2024-07-24 16:48 UTC, A5rocks commented on app/__main__.py
> +    await interaction.response.send_message(embed=embed, view=view)
If so, then my first comment about sending a new message instead of editing might be incorrect: I think in that case you should just edit the embed.

2024-07-25 17:25 UTC, LuckElixir commented
Does the current implementation of `UpgradeView` work? I do agree with having an ephemeral message and editing it instead of sending a new message every time, but the embed would only change the cost and possibly the description depending on the user profile.

2024-07-25 18:18 UTC, A5rocks commented
Hmm, I'm not sure: I imagine the process to be: /upgrade, I get an ephemeral menu, I can upgrade and still upgrade again afterwards (so no changing buttons) with up to date prices (so edit the embed).

I don't think that's exactly what we have here yet

2024-07-25 21:07 UTC, LuckElixir commented
The current implementation (the new commit) assumes that the user already has a profile (as it calls `client.database.get_profile`), meaning that the implementation will break if the upgrade command is not restricted to people with profiles (and whether or not it is enabled in the channel). Should I also add an `upgrade` method  that would actually update the stats of the user?

2024-07-25 22:00 UTC, A5rocks commented
I think we currently handle making new profiles if there are none in the database right? Shouldn't it work?

Cause when I tested /send I used the profile (to get CPS) and that seemed to work.

2024-07-26 00:55 UTC, LuckElixir commented
Oh yeah, completely forgot about the `defaultdict` being there. I think that should work then, although I feel like there should be an implementation of an upgrade method, or is this good enough as is?

2024-07-26 01:18 UTC, A5rocks commented
Probably good enough as is, feel free to make a follow up issue

2024-07-26 01:18 UTC, A5rocks approved these changes

2024-07-26 01:30 UTC, merged