Implement `/send`
A5rocks/code-jam-11 pull request #34
Opened 2024-07-25 04:17 UTC by A5rocks

Fixes https://github.com/A5rocks/code-jam-11/issues/22

2024-07-25 17:31 UTC, aceeedev requested changes
bug: it seems when you /send two messages, both messages get slowly added/edited together

example:
/send test message
/send 1234567890
output: test 1m2e3s4s5a6g7e890

2024-07-25 18:04 UTC, A5rocks commented
Yeah it should probably be per-user right? Like it adds to a buffer per user?

2024-07-25 18:25 UTC, LuckElixir commented
Isn't the combination of messages supposed to be intentional?

2024-07-25 18:31 UTC, A5rocks commented
> Isn't the combination of messages supposed to be intentional?

Yes but only across different users; if the same user sends multiple messages they shouldn't multiplex.

2024-07-26 05:04 UTC, aceeedev submitted a review, later dismissed

2024-07-26 05:04 UTC, aceeedev commented on app/__main__.py
> +    if interaction.channel not in interaction.client.database.get_enabled_channels(interaction.guild):
database.get_enabled_channels has been replaced with database.get_channels I believe and also needs to be awaited

2024-07-26 05:04 UTC, aceeedev commented on app/sender.py
> +        profile = client.database.get_profile(where.guild, p)
database.get_profile needs to be awaited too

2024-07-26 05:47 UTC, aceeedev approved these changes

2024-07-26 06:01 UTC, merged